// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCipiGDmW_pqa1uTlCEtOBhQv2msSZjGFg',
    appId: '1:559171186326:web:6742ad3bb1f19c3c551cb7',
    messagingSenderId: '559171186326',
    projectId: 'gaza-martyer-app',
    authDomain: 'gaza-martyer-app.firebaseapp.com',
    storageBucket: 'gaza-martyer-app.firebasestorage.app',
    measurementId: 'G-M0XTB7BR8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZwR3zh1JujvYFTOkUZm-d-Cq_IC1RIU',
    appId: '1:559171186326:android:be54c1d02f0d3bdc551cb7',
    messagingSenderId: '559171186326',
    projectId: 'gaza-martyer-app',
    storageBucket: 'gaza-martyer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyM21b7eEsG1VHyrk_h8SlmdEzSd2yH94',
    appId: '1:559171186326:ios:291b5277a6af9756551cb7',
    messagingSenderId: '559171186326',
    projectId: 'gaza-martyer-app',
    storageBucket: 'gaza-martyer-app.firebasestorage.app',
    iosBundleId: 'com.example.gazaMartyerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyM21b7eEsG1VHyrk_h8SlmdEzSd2yH94',
    appId: '1:559171186326:ios:291b5277a6af9756551cb7',
    messagingSenderId: '559171186326',
    projectId: 'gaza-martyer-app',
    storageBucket: 'gaza-martyer-app.firebasestorage.app',
    iosBundleId: 'com.example.gazaMartyerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCipiGDmW_pqa1uTlCEtOBhQv2msSZjGFg',
    appId: '1:559171186326:web:9997709efba51851551cb7',
    messagingSenderId: '559171186326',
    projectId: 'gaza-martyer-app',
    authDomain: 'gaza-martyer-app.firebaseapp.com',
    storageBucket: 'gaza-martyer-app.firebasestorage.app',
    measurementId: 'G-PHSC0S9K1L',
  );
}
